// <auto-generated />
using System;
using ForecastingWorkingPopulation.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForecastingWorkingPopulation.Migrations
{
    [DbContext(typeof(PopulationContext))]
    [Migration("20250330123118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ForecastingWorkingPopulation.Database.Models.EmployedEconomyPopulationInRegionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EmployedEconomyPopulations");
                });

            modelBuilder.Entity("ForecastingWorkingPopulation.Database.Models.PermanentPopulationInRegionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PermanentPopulations");
                });

            modelBuilder.Entity("ForecastingWorkingPopulation.Database.Models.RegionCoefficientSettingsEntity", b =>
                {
                    b.Property<int>("RegionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coefficient2019")
                        .HasColumnType("REAL");

                    b.Property<double>("Coefficient2020")
                        .HasColumnType("REAL");

                    b.Property<double>("Coefficient2021")
                        .HasColumnType("REAL");

                    b.Property<double>("Coefficient2022")
                        .HasColumnType("REAL");

                    b.Property<double>("Coefficient2023")
                        .HasColumnType("REAL");

                    b.Property<double>("Coefficient2024")
                        .HasColumnType("REAL");

                    b.Property<decimal>("CoefficientLimit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisableCoefficientCutoff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAge")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegionNumber");

                    b.ToTable("RegionCoefficientSettings");
                });

            modelBuilder.Entity("ForecastingWorkingPopulation.Database.Models.RegionInfoEntity", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Number");

                    b.ToTable("Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
